### ISSUE TITLE
Clidantic gets extra argument when only one command is set

### ISSUE THREAD

**Issue by fabiomontello** [edornd/clidantic#5]
When having a main file with only one command, this is not subgrouped by default, and if the user tries to use it as subcommand, it gets an error which is not self explainatory.

Example:
``` from typing import Optional
from pydantic import BaseModel

from clidantic import Parser

class Arguments(BaseModel):
    field_a: str
    field_b: int
    field_c: Optional[bool] = False

cli = Parser()


@cli.command()
def run(args: Arguments):
    print(args)


if __name__ == "__main__":
    cli()
```
    
when the following command is run:
   
```python3 main.py run a=hola b=1337```

the following error is returned:
```
Usage: main.py [OPTIONS]
Try 'main.py --help' for help.

Error: Got unexpected extra argument (run)
```

**Comment by edornd** [comment]
Just for the record, this is actually the expected behaviour: running the following click example as `python main.py hello`:
```python
import click

@click.command()
@click.option("--count", default=1, help="Number of greetings.")
@click.option("--name", prompt="Your name", help="The person to greet.")
def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for x in range(count):
        click.echo(f"Hello {name}!")


if __name__ == "__main__":
    hello()
```
Will also output `Error: Got unexpected extra argument (hello)`.
Currently, a single command is not grouped by default, so that the behaviour remains consistent with its native CLI library.
That said, it is true that the message is not self-explanatory and we are not required to stick with it.
